name: website

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy to website branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        submodules: 'recursive'
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Deloy websites
      run: |
        cd website
        ./deploy.sh
